version: '3'
services:
    backend:
        image: marcoshenriqueb/epraja-backend
        environment:
            NODE_ENV: "production"
        ports:
            - "3030:3030"
    mongo:
        image: mongo
        volumes:
            - ~/.mongodb:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: sylvia
            MONGO_INITDB_ROOT_PASSWORD: epraja2017
        ports:
            - "27017:27017"
    nginx:
        image: marcoshenriqueb/epraja-frontend
        ports:
            - "80:80"
